In [28]:
import numpy as np
import pandas as pd

### Dataframes

In [30]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [31]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

### Series

In [34]:
type(df['Make'])

pandas.Series

In [35]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [37]:
df[['Make', 'Model', 'Year']]

      Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

In [39]:
df['id'] = [10, 20, 30, 40, 50]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

### Index & Accesing elements

In [40]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [43]:
df.loc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30

In [44]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [46]:
df.loc[["b", "c"]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30

In [47]:
df.iloc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30

In [49]:
df.reset_index(drop=True, inplace=True)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

### Element-wise operations

In [50]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [52]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

### Filtering

In [53]:
df[df['Year'] >= 2015]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [54]:
df[df['Make'] == 'Nissan']

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [55]:
df[
    (df['Make'] == 'Nissan')
    & (df['Year'] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

### String operations

In [56]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [57]:
df['Vehicle_Style'].str.upper()

0          SEDAN
1          SEDAN
2    CONVERTIBLE
3        4DR SUV
4         PICKUP
Name: Vehicle_Style, dtype: str

In [59]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340,50

### Summarizing operations

In [61]:
df['MSRP'].mean()

np.float64(30186.0)

In [62]:
df['MSRP'].max()

np.int64(54990)

In [63]:
df['MSRP'].min()

np.int64(2000)

In [64]:
df['MSRP'].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [65]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP         id
count     5.000000    4.00000          5.000000      5.000000   5.000000
mean   2010.400000  202.75000          4.400000  30186.000000  30.000000
std      11.260551   51.29896          0.894427  18985.044904  15.811388
min    1991.000000  138.00000          4.000000   2000.000000  10.000000
25%    2010.000000  180.00000          4.000000  27150.000000  20.000000
50%    2017.000000  206.00000          4.000000  32340.000000  30.000000
75%    2017.000000  228.75000          4.000000  34450.000000  40.000000
max    2017.000000  261.00000          6.000000  54990.000000  50.000000

In [66]:
df['Make'].nunique()

4

In [68]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
id                   5
dtype: int64

### Missing values

In [67]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

### Grouping

In [70]:
df.groupby('Transmission Type')['MSRP'].mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64